export const projectsData = {
    web: [
      {
        titleKey: "projects.web.salonderechazados.title",
        descriptionKey: "projects.web.salonderechazados.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmo3hwy0nhks507n5trrkycq0",
        imageHint: "cinema community site",
        repoLink: "https://github.com/moonthang/SalonDeRechazados",
        demoLink: "https://salon-de-rechazados.vercel.app/",
        technologies: [
          { name: "Next.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg" },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
          { name: "Tailwind", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg" },
          { name: "ShadCN UI", icon: "https://images.seeklogo.com/logo-png/51/2/shadcn-ui-logo-png_seeklogo-519786.png" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
          { name: "Hygraph", icon: "https://hygraph.com/favicon.png" },
          { name: "Lucide Icons", icon: "https://lucide.dev/logo.dark.svg" },
          { name: "Zod", icon: "https://zod.dev/logo.svg" },
          { name: "React Hook Form", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" }
        ],
      },
      {
        titleKey: "projects.web.yuwelongo.title",
        descriptionKey: "projects.web.yuwelongo.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmidrhe5gyo4n08lpr964yctk",
        imageHint: "interactive dictionary",
        repoLink: "https://github.com/moonthang/yuwelongo-frontend",
        backendRepoLink: "https://github.com/moonthang/yuwelongo-backend",
        videoUrl: "https://youtu.be/OxFrey1TGNg",
        technologies: [
          { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Java", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" },
          { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
          { name: "Jakarta EE", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" },
          { name: "JWT", icon: "https://img.icons8.com/?size=100&id=rHpveptSuwDz&format=png&color=000000" },
          { name: "MySQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" },
          { name: "Eclipse GlassFish", icon: "https://w7.pngwing.com/pngs/4/908/png-transparent-glassfish-java-platform-enterprise-edition-computer-servers-netbeans-operations-support-system-white-text-logo.png" },
          { name: "BCrypt", icon: "https://img.icons8.com/ios-filled/50/lock.png" },
        ],
      },
      {
        titleKey: "projects.web.futdraft.title",
        descriptionKey: "projects.web.futdraft.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmdukgon5p3wk07n1ys13cf3j",
        imageHint: "soccer draft app",
        repoLink: "https://github.com/moonthang/1vs1",
        demoLink: "https://1vs1.vercel.app/",
        technologies: [
          { name: "Next.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg" },
          { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
          { name: "Tailwind", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg" },
          { name: "ShadCN UI", icon: "https://images.seeklogo.com/logo-png/51/2/shadcn-ui-logo-png_seeklogo-519786.png" },
          { name: "Zustand", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Lucide Icons", icon: "https://lucide.dev/logo.dark.svg" },
          { name: "React Select", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "html-to-image", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" }
        ],
      },
      {
        titleKey: "projects.web.petlink.title",
        descriptionKey: "projects.web.petlink.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme5t6337iy0v07n27yevapak",
        imageHint: "pet safety app",
        repoLink: "https://github.com/moonthang/Pet-Link",
        demoLink: "https://pet-link-azure.vercel.app/",
        technologies: [
          { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
          { name: "Tailwind", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg" },
          { name: "ShadCN UI", icon: "https://images.seeklogo.com/logo-png/51/2/shadcn-ui-logo-png_seeklogo-519786.png" },
          { name: "qrcode.react", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Google Maps JavaScript API", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg" },
          { name: "Lucide Icons", icon: "https://lucide.dev/logo.dark.svg" },
        ],
      },
      {
        titleKey: "projects.web.forofinanzas.title",
        descriptionKey: "projects.web.forofinanzas.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmp1ypodc98i308lt2ux01g2y",
        imageHint: "Foro de finanzas ladingpage",
        demoLink: "https://dev-pruebaforofinanzas.pantheonsite.io/",
        technologies: [
          { name: "Wordpress", icon: "https://cdn.jsdelivr.net/npm/@wordpress/icons@13.0.0/+esm" },
        ],
      },
       {
        titleKey: "projects.web.coonadoc.title",
        descriptionKey: "projects.web.coonadoc.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme5t633ciy1007n2h8x20xpg",
        imageHint: "cooperative website",
        repoLink: "https://github.com/moonthang/Sitio-web-Coondoc",
        demoLink: "https://desarrollo-front-angular-19.vercel.app/",
        technologies: [
          { name: "HTML5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
          { name: "CSS3", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
          { name: "Angular", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg" },
          { name: "Bootstrap", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
        ],
      },
      {
        titleKey: "projects.web.picasyfijas.title",
        descriptionKey: "projects.web.picasyfijas.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme5tmcqfj80p07n2uu5gokr1",
        imageHint: "logic game",
        repoLink: "https://github.com/moonthang/PicasYFijas",
        demoLink: "#",
        technologies: [
          { name: "C#", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg" },
        ],
      },
      {
        titleKey: "projects.web.textencryptor.title",
        descriptionKey: "projects.web.textencryptor.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme5tmcr4j80v07n2ipd29b7v",
        imageHint: "text encryption tool",
        repoLink: "https://github.com/moonthang/ChallengeONE-EncriptadorDeTexto",
        demoLink: "https://moonthang.github.io/ChallengeONE-EncriptadorDeTexto/",
        technologies: [
          { name: "HTML5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
          { name: "CSS3", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
          { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
        ],
      },
    ],
    mobile: [
      {
        titleKey: "projects.mobile.nexwork.title",
        descriptionKey: "projects.mobile.nexwork.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmidq6itwxa8j08lpibikdgv6",
        imageHint: "mobile app marketplace",
        repoLink: "https://github.com/moonthang/NexWork",
        videoUrl: "https://youtu.be/qYXkySccLR0",
        technologies: [
          { name: "Kotlin", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
          { name: "Material Design", icon: "https://camo.githubusercontent.com/09ec41ecd76b6721b96fb2cec981f17621adcd6f16ee007d915b9ea51101633e/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f64657669636f6e732f64657669636f6e2f69636f6e732f6d6174657269616c75692f6d6174657269616c75692d6f726967696e616c2e737667" },
          { name: "Glide", icon: "https://github.com/bumptech/glide/raw/master/static/glide_logo.png?raw=true" },
          { name: "Jetpack", icon: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh4w0oGQjFQJFWtOj0Qa8SwrBirBNlVHJpcKOghOH1fIDCKrsQqSX5H6EcJ_20awS9k3gBPeauTCco426eT73CNVY_UIS6BYHt5VQwK9-DNSJIxRyEOfpdeD9bIvcEiLjcGD7EaKtDu5i4/s1600/Jetpack-nav-icon.png" },
        ],
      },
    ],
    graphic: [
      {
        titleKey: "projects.graphic.sdr.title",
        descriptionKey: "projects.graphic.sdr.description",
        imageUrl: "https://us-west-2.graphassets.com/cmnqecy34054e08lsedmvdfa0/cmoc5vwntxvjz07n12pizmrwf",
        imageHint: "Salón de Rechazados | Análisis de Películas y Ensayos de Cine",
        figmaEmbedUrl: "https://us-west-2.graphassets.com/cmnqecy34054e08lsedmvdfa0/cmoc5pcc9y04g07n3f5b9kicp",
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
      {
        titleKey: "projects.graphic.toshiro.title",
        descriptionKey: "projects.graphic.toshiro.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4dlats9c007liaq5wrnok",
        imageHint: "sushi restaurant carousel",
        imageUrls: [
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej2fegsq20m07mzon0ola58",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej2feg7q20g07mzbdwhvot2",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej2feg5q0yo07li570qweaj"
        ],
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
      {
        titleKey: "projects.graphic.coopfiligrana.title",
        descriptionKey: "projects.graphic.coopfiligrana.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmekgjgzkf5x407lid8hpszzy",
        imageHint: "cooperative stories carousel",
        imageUrls: [
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4ktm7sl4f07mzbmhdrbzc",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4ktmosl4m07mz60c13hg7",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4ktmpsl4o07mzd5yicjo4",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4ktm3siwc07li33cvgdn8"
        ],
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
      {
        titleKey: "projects.graphic.pendonTauck.title",
        descriptionKey: "projects.graphic.pendonTauck.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbj089la0oy07mvwozts5y7",
        imageHint: "pendon Todo a un Click",
        imageUrls: [
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbj08cha0p507mvv2a312xc",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbj089la0oy07mvwozts5y7",
        ],
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
      {
        titleKey: "projects.graphic.productosTauck.title",
        descriptionKey: "projects.graphic.productosTauck.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbnz26ne66y07mvzo3jwsn7",
        imageHint: "Historias productos Todo a un Click",
        imageUrls: [
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlihladla07mvnot6kbzk",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlidradl307mvrtfr1mm8",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlil8adlh07mvce3y3q4l",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjmwoaagli07lqzkzga7jo",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjmwl4ael907mvbeg6d628",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjmwikael207mvsln017gy",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjmwfvaekv07mv82vhvjae",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjmwcnagl907lq5bbwhn9e",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlyxtag0407lqslhp2dtg",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlyuzae4s07mv3j0vk89v",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlys8ae4l07mv0qe6nreu",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlyotafzw07lqt2g7x0zi",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlym4ae4e07mvwocuzvgs",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlyjpafzp07lqe8v6wpid",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjlyhcafzg07lqd5tnwvxd",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkz6vad7w07mvyrpeu3b0",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkz3waewc07lq2kk5kbpc",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkz13ad7n07mvk51opjpy",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkyxuad7807mv29k62cvd",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkyuvaevx07lqva8boucf",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkys7aevq07lqk5q748fy",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkyq0ad7107mv0cqvfvq9",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkyncad6u07mvqnbd1n9p",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkyjvaevb07lqr9osoqxx",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjkyh4ad6j07mvwey6ug62",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7dvadhc07lqm4m0i5nc",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7awadh507lq6tax0i1q",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj77sadgy07lq4bdl1lox",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj74pac8u07mve06k14tx",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj6yoac8n07mvme47eqtz",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj6w2adgk07lqvyq1tixn",
        ],
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
      {
        titleKey: "projects.graphic.hBlogTauck.title",
        descriptionKey: "projects.graphic.hBlogTauck.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbnz2bve1m207lqs1e14j88",
        imageHint: "Historias noticias blog Todo a un Click",
        imageUrls: [
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjk7ijacp807mv1c0ua4gy",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjk7faae2j07lqfz1vuawk",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjk7c9acp107mvcodkzmcu",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjk795ae2c07lqhh3v6swi",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjk764ae2507lq0htv52ww",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjk732acou07mv4yna2txy",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7h5ac9307mv8pby7c6f",
        ],
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
      {
        titleKey: "projects.graphic.otrosTauck.title",
        descriptionKey: "projects.graphic.otrosTauck.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbnz2ene67507mvgelz6441",
        imageHint: "Otros diseños para Todo a un Click",
        imageUrls: [
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbiof6f9thz07mvdooimo1r",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj820adia07lqbjbzmb64",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbiq0rk9v9a07lqpewmkzm5",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7k5adhj07lq6hmy1ka4",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7wiaca507mve7nukq5l",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7zgadi307lqae08zrcw",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7paac9q07mv7z0ml31r",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7t5ac9y07mvh49esw9e",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbios639tmj07mvrcvdy6ez",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmpbjj7mzadhq07lqc077m0dz",
        ],
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
    ],
    ui_ux: [
      {
        titleKey: "projects.uiux.smarthome.title",
        descriptionKey: "projects.uiux.smarthome.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmoerfuid3xh007lqe2fgpp9z",
        imageHint: "dashboard mockup smart home",
        figmaEmbedUrl: "https://embed.figma.com/design/YmXUjCVaAFrzD5lpwf9hx2/SmartHome?node-id=0-1&embed-host=share",
        technologies: [
          { name: "Figma", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
        ],
      },
      {
        titleKey: "projects.uiux.sbcleanco.title",
        descriptionKey: "projects.uiux.sbcleanco.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme797xi8anm007my6f6hpb8u",
        imageHint: "website mockup cleaning service",
        figmaEmbedUrl: "https://embed.figma.com/proto/AQ6BOOd6xQRNSHJgGkBElg/Pages-SBC?node-id=2-26&embed-host=share",
        technologies: [
          { name: "Figma", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
        ],
      },
      {
        titleKey: "projects.uiux.FlowSync.title",
        descriptionKey: "projects.uiux.FlowSync.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmobxskjvkto207n1qdauf6ot",
        imageHint: "Ladingpage website mockup FlowSync",
        figmaEmbedUrl:"https://embed.figma.com/design/Ne8UA6zekcsXQNnCsS7chI/FlowSync?node-id=1-202&embed-host=share",
        technologies: [
          { name: "Figma", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
        ],
      },
    ],
  };