export const projectsData = {
    web: [
      {
        titleKey: "projects.web.salonderechazados.title",
        descriptionKey: "projects.web.salonderechazados.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmo3hwy0nhks507n5trrkycq0",
        imageHint: "cinema community site",
        repoLink: "https://github.com/moonthang/SalonDeRechazados",
        demoLink: "https://salon-de-rechazados.vercel.app/",
        technologies: [
          { name: "Next.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg" },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
          { name: "Tailwind", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg" },
          { name: "ShadCN UI", icon: "https://images.seeklogo.com/logo-png/51/2/shadcn-ui-logo-png_seeklogo-519786.png" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
          { name: "Hygraph", icon: "https://hygraph.com/favicon.png" },
          { name: "Lucide Icons", icon: "https://lucide.dev/logo.dark.svg" },
          { name: "Zod", icon: "https://zod.dev/logo.svg" },
          { name: "React Hook Form", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" }
        ],
      },
      {
        titleKey: "projects.web.yuwelongo.title",
        descriptionKey: "projects.web.yuwelongo.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmidrhe5gyo4n08lpr964yctk",
        imageHint: "interactive dictionary",
        repoLink: "https://github.com/moonthang/yuwelongo-frontend",
        backendRepoLink: "https://github.com/moonthang/yuwelongo-backend",
        videoUrl: "https://youtu.be/OxFrey1TGNg",
        technologies: [
          { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Java", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" },
          { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
          { name: "Jakarta EE", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg" },
          { name: "JWT", icon: "https://img.icons8.com/?size=100&id=rHpveptSuwDz&format=png&color=000000" },
          { name: "MySQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" },
          { name: "Eclipse GlassFish", icon: "https://w7.pngwing.com/pngs/4/908/png-transparent-glassfish-java-platform-enterprise-edition-computer-servers-netbeans-operations-support-system-white-text-logo.png" },
          { name: "BCrypt", icon: "https://img.icons8.com/ios-filled/50/lock.png" },
        ],
      },
      {
        titleKey: "projects.web.futdraft.title",
        descriptionKey: "projects.web.futdraft.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmdukgon5p3wk07n1ys13cf3j",
        imageHint: "soccer draft app",
        repoLink: "https://github.com/moonthang/1vs1",
        demoLink: "https://1vs1.vercel.app/",
        technologies: [
          { name: "Next.js", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg" },
          { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
          { name: "Tailwind", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg" },
          { name: "ShadCN UI", icon: "https://images.seeklogo.com/logo-png/51/2/shadcn-ui-logo-png_seeklogo-519786.png" },
          { name: "Zustand", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Lucide Icons", icon: "https://lucide.dev/logo.dark.svg" },
          { name: "React Select", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "html-to-image", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" }
        ],
      },
      {
        titleKey: "projects.web.petlink.title",
        descriptionKey: "projects.web.petlink.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme5t6337iy0v07n27yevapak",
        imageHint: "pet safety app",
        repoLink: "https://github.com/moonthang/Pet-Link",
        demoLink: "https://pet-link-azure.vercel.app/",
        technologies: [
          { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
          { name: "Tailwind", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg" },
          { name: "ShadCN UI", icon: "https://images.seeklogo.com/logo-png/51/2/shadcn-ui-logo-png_seeklogo-519786.png" },
          { name: "qrcode.react", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" },
          { name: "Google Maps JavaScript API", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/google/google-original.svg" },
          { name: "Lucide Icons", icon: "https://lucide.dev/logo.dark.svg" },
        ],
      },
       {
        titleKey: "projects.web.coonadoc.title",
        descriptionKey: "projects.web.coonadoc.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme5t633ciy1007n2h8x20xpg",
        imageHint: "cooperative website",
        repoLink: "https://github.com/moonthang/Sitio-web-Coondoc",
        demoLink: "https://desarrollo-front-angular-19.vercel.app/",
        technologies: [
          { name: "HTML5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
          { name: "TypeScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" },
          { name: "CSS3", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
          { name: "Angular", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg" },
          { name: "Bootstrap", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
        ],
      },
      {
        titleKey: "projects.web.picasyfijas.title",
        descriptionKey: "projects.web.picasyfijas.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme5tmcqfj80p07n2uu5gokr1",
        imageHint: "logic game",
        repoLink: "https://github.com/moonthang/PicasYFijas",
        demoLink: "#",
        technologies: [
          { name: "C#", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg" },
        ],
      },
      {
        titleKey: "projects.web.textencryptor.title",
        descriptionKey: "projects.web.textencryptor.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme5tmcr4j80v07n2ipd29b7v",
        imageHint: "text encryption tool",
        repoLink: "https://github.com/moonthang/ChallengeONE-EncriptadorDeTexto",
        demoLink: "https://moonthang.github.io/ChallengeONE-EncriptadorDeTexto/",
        technologies: [
          { name: "HTML5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" },
          { name: "CSS3", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" },
          { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" },
        ],
      },
    ],
    mobile: [
      {
        titleKey: "projects.mobile.nexwork.title",
        descriptionKey: "projects.mobile.nexwork.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmidq6itwxa8j08lpibikdgv6",
        imageHint: "mobile app marketplace",
        repoLink: "https://github.com/moonthang/NexWork",
        videoUrl: "https://youtu.be/qYXkySccLR0",
        technologies: [
          { name: "Kotlin", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg" },
          { name: "Firebase", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg" },
          { name: "Material Design", icon: "https://camo.githubusercontent.com/09ec41ecd76b6721b96fb2cec981f17621adcd6f16ee007d915b9ea51101633e/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f64657669636f6e732f64657669636f6e2f69636f6e732f6d6174657269616c75692f6d6174657269616c75692d6f726967696e616c2e737667" },
          { name: "Glide", icon: "https://github.com/bumptech/glide/raw/master/static/glide_logo.png?raw=true" },
          { name: "Jetpack", icon: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh4w0oGQjFQJFWtOj0Qa8SwrBirBNlVHJpcKOghOH1fIDCKrsQqSX5H6EcJ_20awS9k3gBPeauTCco426eT73CNVY_UIS6BYHt5VQwK9-DNSJIxRyEOfpdeD9bIvcEiLjcGD7EaKtDu5i4/s1600/Jetpack-nav-icon.png" },
        ],
      },
    ],
    graphic: [
      {
        titleKey: "projects.graphic.sdr.title",
        descriptionKey: "projects.graphic.sdr.description",
        imageUrl: "https://us-west-2.graphassets.com/cmnqecy34054e08lsedmvdfa0/cmoc5vwntxvjz07n12pizmrwf",
        imageHint: "Salón de Rechazados | Análisis de Películas y Ensayos de Cine",
        figmaEmbedUrl: "https://us-west-2.graphassets.com/cmnqecy34054e08lsedmvdfa0/cmoc5pcc9y04g07n3f5b9kicp",
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
      {
        titleKey: "projects.graphic.toshiro.title",
        descriptionKey: "projects.graphic.toshiro.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4dlats9c007liaq5wrnok",
        imageHint: "sushi restaurant carousel",
        imageUrls: [
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej2fegsq20m07mzon0ola58",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej2feg7q20g07mzbdwhvot2",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej2feg5q0yo07li570qweaj"
        ],
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
      {
        titleKey: "projects.graphic.coopfiligrana.title",
        descriptionKey: "projects.graphic.coopfiligrana.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmekgjgzkf5x407lid8hpszzy",
        imageHint: "cooperative stories carousel",
        imageUrls: [
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4ktm7sl4f07mzbmhdrbzc",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4ktmosl4m07mz60c13hg7",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4ktmpsl4o07mzd5yicjo4",
          "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmej4ktm3siwc07li33cvgdn8"
        ],
        technologies: [
          { name: "Photoshop", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/photoshop/photoshop-plain.svg" },
          { name: "Illustrator", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/illustrator/illustrator-plain.svg" },
        ],
      },
    ],
    ui_ux: [
      {
        titleKey: "projects.uiux.smarthome.title",
        descriptionKey: "projects.uiux.smarthome.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmoerfuid3xh007lqe2fgpp9z",
        imageHint: "dashboard mockup smart home",
        figmaEmbedUrl: "https://embed.figma.com/design/YmXUjCVaAFrzD5lpwf9hx2/SmartHome?node-id=0-1&embed-host=share",
        technologies: [
          { name: "Figma", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
        ],
      },
      {
        titleKey: "projects.uiux.sbcleanco.title",
        descriptionKey: "projects.uiux.sbcleanco.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cme797xi8anm007my6f6hpb8u",
        imageHint: "website mockup cleaning service",
        figmaEmbedUrl: "https://embed.figma.com/proto/AQ6BOOd6xQRNSHJgGkBElg/Pages-SBC?node-id=2-26&embed-host=share",
        technologies: [
          { name: "Figma", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
        ],
      },
      {
        titleKey: "projects.uiux.FlowSync.title",
        descriptionKey: "projects.uiux.FlowSync.description",
        imageUrl: "https://us-west-2.graphassets.com/cmdc30lgu1tuj06n2dtwpe500/cmobxskjvkto207n1qdauf6ot",
        imageHint: "Ladingpage website mockup FlowSync",
        figmaEmbedUrl:"https://embed.figma.com/design/Ne8UA6zekcsXQNnCsS7chI/FlowSync?node-id=1-202&embed-host=share",
        technologies: [
          { name: "Figma", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg" },
        ],
      },
    ],
  };